### ISSUE TITLE
Implicit declaration of function 'YMCSwizzler' is invalid in C99

### ISSUE THREAD

**Issue by wakiki** [ymc-thzi/PhysicsDebugger#4]
I'm getting the following error which blocks the Pod from working at all - 

http://d.pr/i/tnty

'Implicit declaration of function 'YMCSwizzler' is invalid in C99'

Am using XCode 5.0.2 on iOS Simulator (iphone Retina 4 inch)

Any ideas?

Steve

**Comment by ymc-thzi** [comment]
Unfortunately I will not maintain this little tool anymore because Apple added a built in debugging property since iOS 7.1
So I think it's better to use this one.
