### ISSUE TITLE
PhysicsDebug boxes not showing or mis-sized if in child node of scene

### ISSUE THREAD

**Issue by wakiki** [ymc-thzi/PhysicsDebugger#5]
I thought I would open a separate issue to keep things clear. 

I did some tests and it looks like all nodes must be direct children of the scene to work. So for example the code below will fail.

Is this a bug? Just wondering as Apple's Adventure example actively encourage people to put nodes under layers, and a car would for example have many children nodes.

Steve

```
    SKNode *layer = [[SKNode alloc] init];
    [self addChild:layer];
    
    //a sprite with a rectangle physicsBody
    SKSpriteNode* box = [SKSpriteNode spriteNodeWithImageNamed:@"mole"];
    box.name = @"box";
    box.physicsBody = [SKPhysicsBody bodyWithRectangleOfSize:CGSizeMake(80, 80)];
    box.physicsBody.mass = 0.1;
    box.position = CGPointMake(self.size.width/2,self.size.height-10);
    [layer addChild:box];
```

**Comment by ymc-thzi** [comment]
Unfortunately I will not maintain this little tool anymore because Apple added a built in debugging property since iOS 7.1
So I think it's better to use this one.
