### ISSUE TITLE
Circular physicbodies fail in 64-bit iOS Simulator

### ISSUE THREAD

**Issue by wakiki** [ymc-thzi/PhysicsDebugger#6]
Again, I've put this as a separate issue to keep things clear:

bodyWithCircleOfRadius produces malloc error, as in the following code for example (and also in the demo project)

```
    //a sprite with a circle physicsBody
    SKSpriteNode* ball = [SKSpriteNode spriteNodeWithImageNamed:@"ball"];
    ball.name = @"ball";
    ball.position = CGPointMake(self.size.width/2,self.size.height-1);
    ball.physicsBody = [SKPhysicsBody bodyWithCircleOfRadius:ball.size.width/2];
    [self addChild:ball];
```
This is the error:
http://d.pr/i/Lhr7

```
PhysicsDebugger(52095,0x10214c310) malloc: *** error for object 0x109f52e90: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

The error occurs with 64-bit simulators but not the 32-bit ones - any ideas?

Thanks!

Steve

**Comment by ymc-thzi** [comment]
Unfortunately I will not maintain this little tool anymore because Apple added a built in debugging property since iOS 7.1
So I think it's better to use this one.
